arii_stat:
    path:     /stat
    defaults: { _controller: StatBundle:Default:index }



xml_Stat_date_form:
  pattern: /jobs/form_date.xml
  defaults: {_controller: StatBundle:Default:form_date}

########## Charts ##################################
box_chart:
  path: /boxplot
  defaults: { _controller: StatBundle:Chart:boxplot }

box_chart_json:
  path: /boxplot.json
  defaults: { _controller: StatBundle:Data:boxplot }


pie_chart:
  path: /piechart
  defaults: { _controller: StatBundle:Chart:piechart }

pie_chart_json:
  path: /piechart.json
  defaults: { _controller: StatBundle:Data:piechart }

bar_chart:
  path: /barchart
  defaults: { _controller: StatBundle:Chart:barchart }

bar_chart_json:
  path: /barchart.json
  defaults: { _controller: StatBundle:Data:barchart }

line_chart:
  path: /linechart
  defaults: { _controller: StatBundle:Chart:linechart }

line_chart_json:
  path: /linechart.json
  defaults: { _controller: StatBundle:Data:linechart}

line_chart_pred_json:
  path: /linechart_pred.json
  defaults: { _controller: StatBundle:Data:linechartPred}


### data ####

dataframe_xml:
  path: /dataframe
  defaults: { _controller: StatBundle:Data:dataframe }

anomaly_xml:
  path: /anomaly
  defaults: { _controller: StatBundle:Data:anomaly}


describe_xml:
  path: /describe
  defaults: { _controller: StatBundle:Data:describe }

Stat_jobs_xml:
  path: /jobs_xml
  defaults: { _controller: StatBundle:Default:jobs }


Stat_job_xml:
  path: /job_xml
  defaults: { _controller: StatBundle:Default:job}


Stat_jobs_date_xml:
  path: /jobs_xml_date/from={date1}/to={date2}
  defaults: { _controller: StatBundle:Default:datedJobs}

Stat_job_history_xml:
  path: /job_xml_history/
  defaults: { _controller: StatBundle:Default:historyJob}
